name: Create deployment status
description: Create deployment status

inputs:
  token:
    description: A token to perform API calls
    required: true
  deployment_id:
    description: deployment id
    required: true
  state:
    description: The state of the status. Can be one of error, failure, inactive, in_progress, queued pending, or success.
    required: true
  log_url:
    description: The full URL of the deployment's output.
    required: false
  description:
    description: A short description of the status. The maximum description length is 140 characters.
    required: false
  environment:
    description: Name for the target deployment environment, which can be changed when setting a deploy status. For example, production, staging, or qa.
    required: false
  environment_url:
    description: Sets the URL for accessing your environment.
    required: false
  auto_inactive:
    description: Adds a new inactive status to all prior non-transient, non-production environment deployments with the same repository and environment name as the created status's deployment. An inactive status is only added to deployments that had a success state
    required: 

runs:
  using: node12
  main: index.js

branding:
  icon: sun
  color: green
